name = "AgentsABMExamples"
authors = ["BAF"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"

[compat]
DrWatson = "2.12.0"
julia = "1.8.2"
